### ISSUE TITLE
Web view delegates not being called

### ISSUE THREAD

**Issue by MaxHasADHD** [brentnycum/BNHtmlPdfKit#6]
I put breakpoints into the web view delegate and added webViewDidStartLoad and nothing is being called for some reason. heres my code.

NSString *documentDirectory = [[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0] stringByAppendingPathComponent:@"google.pdf"];
        BNHtmlPdfKit *pdfKit = [BNHtmlPdfKit saveUrlAsPdf:webView.request.URL toFile:documentDirectory pageSize:BNPageSizeA4 success:^(NSString *filename) {
            NSLog(@"Saved PDF");
        } failure:^(NSError *error) {
            NSLog(@"Faield to save with error: %@",error);
        }];

**Comment by zanekellogg** [comment]
Hi Max,

What was your resolution? I've having the same issue.

Thanks!

**Comment by MaxHasADHD** [comment]
I don't think I had one, hmmm. I was adding support in my app to save web page to PDF, It may be working but i commented it out for now. I think i changed some lines of code from a long time ago.

**Comment by zanekellogg** [comment]
Ok thanks Max. I appreciate the response.

**Comment by arodeus** [comment]
Hi,
same problem here... any solution?

**Comment by zanekellogg** [comment]
It seems like it's all related to retaining the reference. See SO: http://stackoverflow.com/questions/24338560/bnhtmlpdfkit-code-not-doing-anything-on-ios
